### ISSUE TITLE
List.sort should take a function

### ISSUE THREAD

**Issue by TehCupcakes** [Sidorakh/gm-sds#1]
It would be nice if you could sort by function, much like javascript's [Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

There are plenty of use cases where alphanumeric sorting isn't great, like when needing a secondary sort value or working with dates. Also, sorting a list of maps or nested lists won't really be possible without passing a function.

I like the simplicity of being able to do asc and desc without passing a function though. I can think of a few variants on how that might be implemented:

```
sort(cb)
sortAsc()
sortDesc()
```
or maybe
```
sort(cb) - takes a function, but defaults to asc if not provided
reverse() - reverses order of items in list
```
...so you can do `list.sort().reverse()` to get a list in desc order.

**Comment by Sidorakh** [comment]
I can give this a go, from my understanding `.sort` would sort the list in place, so, this probably won't be too bad. As for passing in a function.. also doable, I'll give these a bash and see how it goes

**Comment by Sidorakh** [comment]
Definitely didn't take me several months to make it, I just got massively sidetracked, and then university happened. The sort function on Lists should now take an optional function, and without, defaults to sorting in ascending order. So, like you wrote, to sort in descending order you can just write `my_list.sort().reverse()`, or to sort with a function, it now takes a comparison function, and the entries are sorted based on its output. Will update the readme with proper documentation in a few
